name: CI

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-latest-x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Install multilib
        run: sudo apt install gcc-multilib g++-multilib
      - name: Build
        run: |
          cmake -B build
          cmake --build build --parallel
          cmake --install build --prefix ./install

      - name: Get lowercase OS name
        id: osname
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ runner.os }}

      - name: Move binaries
        run: |
          cp install/bin/libdike.so plugin/addons/dike/binary.so

          
      - name: Compress
        uses: vimtor/action-zip@v1
        with:
          files: plugin/
          dest: dike.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dike.zip
          path: dike.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
          files: dike.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
